# -*- coding: utf-8 -*-
"""
Created on Wed Feb  7 00:28:04 2018

@author: jason
"""

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_event_wizard(object):
    def setupUi(self, event_wizard):
        event_wizard.setObjectName("event_wizard")
        event_wizard.resize(1950, 1116)
        self.centralwidget = QtWidgets.QWidget(event_wizard)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 210, 1881, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox_2 = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_2)
        self.comboBox_4 = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_4)
        self.comboBox_5 = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_5)
        self.comboBox_3 = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_3)
        self.comboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.setItemText(0, "")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(30, 160, 1881, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        event_wizard.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(event_wizard)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1950, 47))
        self.menubar.setObjectName("menubar")
        event_wizard.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(event_wizard)
        self.statusbar.setObjectName("statusbar")
        event_wizard.setStatusBar(self.statusbar)

        self.retranslateUi(event_wizard)
        QtCore.QMetaObject.connectSlotsByName(event_wizard)

    def retranslateUi(self, event_wizard):
        _translate = QtCore.QCoreApplication.translate
        event_wizard.setWindowTitle(_translate("event_wizard", "Event Wizard"))
        self.comboBox_2.setItemText(0, _translate("event_wizard", "0-6"))
        self.comboBox_2.setItemText(1, _translate("event_wizard", "7-8"))
        self.comboBox_2.setItemText(2, _translate("event_wizard", "9-10"))
        self.comboBox_2.setItemText(3, _translate("event_wizard", "11-12"))
        self.comboBox_2.setItemText(4, _translate("event_wizard", "13-14"))
        self.comboBox_2.setItemText(5, _translate("event_wizard", "15-18"))
        self.comboBox_4.setItemText(0, _translate("event_wizard", "Boys"))
        self.comboBox_4.setItemText(1, _translate("event_wizard", "Girls"))
        self.comboBox_4.setItemText(2, _translate("event_wizard", "Men"))
        self.comboBox_4.setItemText(3, _translate("event_wizard", "Women"))
        self.comboBox_5.setItemText(0, _translate("event_wizard", "25 yards"))
        self.comboBox_5.setItemText(1, _translate("event_wizard", "50 yards"))
        self.comboBox_5.setItemText(2, _translate("event_wizard", "100 yards"))
        self.comboBox_5.setItemText(3, _translate("event_wizard", "200 yards"))
        self.comboBox_5.setItemText(4, _translate("event_wizard", "500 yards"))
        self.comboBox_3.setItemText(0, _translate("event_wizard", "Freestyle"))
        self.comboBox_3.setItemText(1, _translate("event_wizard", "Breaststroke"))
        self.comboBox_3.setItemText(2, _translate("event_wizard", "Butterfly"))
        self.comboBox_3.setItemText(3, _translate("event_wizard", "Backstroke"))
        self.comboBox_3.setItemText(4, _translate("event_wizard", "IM"))
        self.comboBox_3.setItemText(5, _translate("event_wizard", "Medley Relay"))
        self.comboBox_3.setItemText(6, _translate("event_wizard", "Freestlye Relay"))
        self.comboBox.setItemText(1, _translate("event_wizard", "1"))
        self.comboBox.setItemText(2, _translate("event_wizard", "2"))
        self.comboBox.setItemText(3, _translate("event_wizard", "3"))
        self.comboBox.setItemText(4, _translate("event_wizard", "4"))
        self.comboBox.setItemText(5, _translate("event_wizard", "5"))
        self.comboBox.setItemText(6, _translate("event_wizard", "6"))
        self.comboBox.setItemText(7, _translate("event_wizard", "7"))
        self.comboBox.setItemText(8, _translate("event_wizard", "8"))
        self.comboBox.setItemText(9, _translate("event_wizard", "9"))
        self.comboBox.setItemText(10, _translate("event_wizard", "10"))
        self.comboBox.setItemText(11, _translate("event_wizard", "11"))
        self.comboBox.setItemText(12, _translate("event_wizard", "12"))
        self.comboBox.setItemText(13, _translate("event_wizard", "13"))
        self.comboBox.setItemText(14, _translate("event_wizard", "14"))
        self.comboBox.setItemText(15, _translate("event_wizard", "15"))
        self.label_5.setText(_translate("event_wizard", "Age"))
        self.label_4.setText(_translate("event_wizard", "Gender"))
        self.label_3.setText(_translate("event_wizard", "Distance"))
        self.label_2.setText(_translate("event_wizard", "Stroke"))
        self.label.setText(_translate("event_wizard", "Heat Number"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    event_wizard = QtWidgets.QMainWindow()
    ui = Ui_event_wizard()
    ui.setupUi(event_wizard)
    event_wizard.show()
    sys.exit(app.exec_())
